[project]
name = "ui-rl"
version = "0.1.0"
description = "RL Finetuning for Computer Use models"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.11.0",
    "datasets>=4.3.0",
    "flash-attn>=2.8.3",
    "ipykernel>=7.1.0",
    "kubernetes>=34.1.0",
    "matplotlib>=3.10.7",
    "peft>=0.17.1",
    "pillow>=11.3.0",
    "tabulate>=0.9.0",
    "vllm>=0.11.0",
]
